import { Component } from '@angular/core';
import { Element } from '../../types/element';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-periodic-table',
  imports: [CommonModule],
  templateUrl: './periodic-table.html',
  styleUrl: './periodic-table.css',
})
export class PeriodicTable {
  elements: Element[] = [
    {
      symbol: 'H',
      name: 'Hydrogen',
      atomicNumber: 1,
      group: 1,
      period: 1,
      type: 'Hydrogen',
    },
    {
      symbol: 'He',
      name: 'Helium',
      atomicNumber: 2,
      group: 18,
      period: 1,
      type: 'Noble-Gas',
    },
    {
      symbol: 'Li',
      name: 'Lithium',
      atomicNumber: 3,
      group: 1,
      period: 2,
      type: 'Alkali-Metal',
    },
    {
      symbol: 'Be',
      name: 'Beryllium',
      atomicNumber: 4,
      group: 2,
      period: 2,
      type: 'Alkali-Earth-Metal',
    },
    {
      symbol: 'B',
      name: 'Boron',
      atomicNumber: 5,
      group: 13,
      period: 2,
      type: 'Metalloid',
    },
    {
      symbol: 'C',
      name: 'Carbon',
      atomicNumber: 6,
      group: 14,
      period: 2,
      type: 'Nonmetal',
    },
    {
      symbol: 'N',
      name: 'Nitrogen',
      atomicNumber: 7,
      group: 15,
      period: 2,
      type: 'Nonmetal',
    },
    {
      symbol: 'O',
      name: 'Oxygen',
      atomicNumber: 8,
      group: 16,
      period: 2,
      type: 'Nonmetal',
    },
    {
      symbol: 'F',
      name: 'Fluorine',
      atomicNumber: 9,
      group: 17,
      period: 2,
      type: 'Nonmetal',
    },
    {
      symbol: 'Ne',
      name: 'Neon',
      atomicNumber: 10,
      group: 18,
      period: 2,
      type: 'Noble-Gas',
    },

    {
      symbol: 'Na',
      name: 'Sodium',
      atomicNumber: 11,
      group: 1,
      period: 3,
      type: 'Alkali-Metal',
    },
    {
      symbol: 'Mg',
      name: 'Magnesium',
      atomicNumber: 12,
      group: 2,
      period: 3,
      type: 'Alkali-Earth-Metal',
    },
    {
      symbol: 'Al',
      name: 'Aluminium',
      atomicNumber: 13,
      group: 13,
      period: 3,
      type: 'Post-Transition-Metal',
    },
    {
      symbol: 'Si',
      name: 'Silicon',
      atomicNumber: 14,
      group: 14,
      period: 3,
      type: 'Metalloid',
    },
    {
      symbol: 'P',
      name: 'Phosphorus',
      atomicNumber: 15,
      group: 15,
      period: 3,
      type: 'Nonmetal',
    },
    {
      symbol: 'S',
      name: 'Sulfur',
      atomicNumber: 16,
      group: 16,
      period: 3,
      type: 'Nonmetal',
    },
    {
      symbol: 'Cl',
      name: 'Chlorine',
      atomicNumber: 17,
      group: 17,
      period: 3,
      type: 'Nonmetal',
    },
    {
      symbol: 'Ar',
      name: 'Argon',
      atomicNumber: 18,
      group: 18,
      period: 3,
      type: 'Noble-Gas',
    },

    {
      symbol: 'K',
      name: 'Potassium',
      atomicNumber: 19,
      group: 1,
      period: 4,
      type: 'Alkali-Metal',
    },
    {
      symbol: 'Ca',
      name: 'Calcium',
      atomicNumber: 20,
      group: 2,
      period: 4,
      type: 'Alkali-Earth-Metal',
    },
    {
      symbol: 'Sc',
      name: 'Scandium',
      atomicNumber: 21,
      group: 3,
      period: 4,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Ti',
      name: 'Titanium',
      atomicNumber: 22,
      group: 4,
      period: 4,
      type: 'Transition-Metal',
    },
    {
      symbol: 'V',
      name: 'Vanadium',
      atomicNumber: 23,
      group: 5,
      period: 4,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Cr',
      name: 'Chromium',
      atomicNumber: 24,
      group: 6,
      period: 4,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Mn',
      name: 'Manganese',
      atomicNumber: 25,
      group: 7,
      period: 4,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Fe',
      name: 'Iron',
      atomicNumber: 26,
      group: 8,
      period: 4,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Co',
      name: 'Cobalt',
      atomicNumber: 27,
      group: 9,
      period: 4,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Ni',
      name: 'Nickel',
      atomicNumber: 28,
      group: 10,
      period: 4,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Cu',
      name: 'Copper',
      atomicNumber: 29,
      group: 11,
      period: 4,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Zn',
      name: 'Zinc',
      atomicNumber: 30,
      group: 12,
      period: 4,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Ga',
      name: 'Gallium',
      atomicNumber: 31,
      group: 13,
      period: 4,
      type: 'Post-Transition-Metal',
    },
    {
      symbol: 'Ge',
      name: 'Germanium',
      atomicNumber: 32,
      group: 14,
      period: 4,
      type: 'Metalloid',
    },
    {
      symbol: 'As',
      name: 'Arsenic',
      atomicNumber: 33,
      group: 15,
      period: 4,
      type: 'Metalloid',
    },
    {
      symbol: 'Se',
      name: 'Selenium',
      atomicNumber: 34,
      group: 16,
      period: 4,
      type: 'Nonmetal',
    },
    {
      symbol: 'Br',
      name: 'Bromine',
      atomicNumber: 35,
      group: 17,
      period: 4,
      type: 'Nonmetal',
    },
    {
      symbol: 'Kr',
      name: 'Krypton',
      atomicNumber: 36,
      group: 18,
      period: 4,
      type: 'Noble-Gas',
    },

    {
      symbol: 'Rb',
      name: 'Rubidium',
      atomicNumber: 37,
      group: 1,
      period: 5,
      type: 'Alkali-Metal',
    },
    {
      symbol: 'Sr',
      name: 'Strontium',
      atomicNumber: 38,
      group: 2,
      period: 5,
      type: 'Alkali-Earth-Metal',
    },
    {
      symbol: 'Y',
      name: 'Yttrium',
      atomicNumber: 39,
      group: 3,
      period: 5,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Zr',
      name: 'Zirconium',
      atomicNumber: 40,
      group: 4,
      period: 5,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Nb',
      name: 'Niobium',
      atomicNumber: 41,
      group: 5,
      period: 5,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Mo',
      name: 'Molybdenum',
      atomicNumber: 42,
      group: 6,
      period: 5,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Tc',
      name: 'Technetium',
      atomicNumber: 43,
      group: 7,
      period: 5,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Ru',
      name: 'Ruthenium',
      atomicNumber: 44,
      group: 8,
      period: 5,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Rh',
      name: 'Rhodium',
      atomicNumber: 45,
      group: 9,
      period: 5,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Pd',
      name: 'Palladium',
      atomicNumber: 46,
      group: 10,
      period: 5,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Ag',
      name: 'Silver',
      atomicNumber: 47,
      group: 11,
      period: 5,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Cd',
      name: 'Cadmium',
      atomicNumber: 48,
      group: 12,
      period: 5,
      type: 'Transition-Metal',
    },
    {
      symbol: 'In',
      name: 'Indium',
      atomicNumber: 49,
      group: 13,
      period: 5,
      type: 'Post-Transition-Metal',
    },
    {
      symbol: 'Sn',
      name: 'Tin',
      atomicNumber: 50,
      group: 14,
      period: 5,
      type: 'Post-Transition-Metal',
    },
    {
      symbol: 'Sb',
      name: 'Antimony',
      atomicNumber: 51,
      group: 15,
      period: 5,
      type: 'Metalloid',
    },
    {
      symbol: 'Te',
      name: 'Tellurium',
      atomicNumber: 52,
      group: 16,
      period: 5,
      type: 'Metalloid',
    },
    {
      symbol: 'I',
      name: 'Iodine',
      atomicNumber: 53,
      group: 17,
      period: 5,
      type: 'Nonmetal',
    },
    {
      symbol: 'Xe',
      name: 'Xenon',
      atomicNumber: 54,
      group: 18,
      period: 5,
      type: 'Noble-Gas',
    },

    {
      symbol: 'Cs',
      name: 'Cesium',
      atomicNumber: 55,
      group: 1,
      period: 6,
      type: 'Alkali-Metal',
    },
    {
      symbol: 'Ba',
      name: 'Barium',
      atomicNumber: 56,
      group: 2,
      period: 6,
      type: 'Alkali-Earth-Metal',
    },
    {
      symbol: 'La',
      name: 'Lanthanum',
      atomicNumber: 57,
      group: 4,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Ce',
      name: 'Cerium',
      atomicNumber: 58,
      group: 5,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Pr',
      name: 'Praseodymium',
      atomicNumber: 59,
      group: 6,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Nd',
      name: 'Neodymium',
      atomicNumber: 60,
      group: 7,
      period: 8,
      type: 'Lanthanide',
    },

    {
      symbol: 'Pm',
      name: 'Promethium',
      atomicNumber: 61,
      group: 8,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Sm',
      name: 'Samarium',
      atomicNumber: 62,
      group: 9,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Eu',
      name: 'Europium',
      atomicNumber: 63,
      group: 10,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Gd',
      name: 'Gadolinium',
      atomicNumber: 64,
      group: 11,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Tb',
      name: 'Terbium',
      atomicNumber: 65,
      group: 12,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Dy',
      name: 'Dysprosium',
      atomicNumber: 66,
      group: 13,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Ho',
      name: 'Holmium',
      atomicNumber: 67,
      group: 14,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Er',
      name: 'Erbium',
      atomicNumber: 68,
      group: 15,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Tm',
      name: 'Thulium',
      atomicNumber: 69,
      group: 16,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Yb',
      name: 'Ytterbium',
      atomicNumber: 70,
      group: 17,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Lu',
      name: 'Lutetium',
      atomicNumber: 71,
      group: 18,
      period: 8,
      type: 'Lanthanide',
    },
    {
      symbol: 'Hf',
      name: 'Hafnium',
      atomicNumber: 72,
      group: 4,
      period: 6,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Ta',
      name: 'Tantalum',
      atomicNumber: 73,
      group: 5,
      period: 6,
      type: 'Transition-Metal',
    },
    {
      symbol: 'W',
      name: 'Tungsten',
      atomicNumber: 74,
      group: 6,
      period: 6,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Re',
      name: 'Rhenium',
      atomicNumber: 75,
      group: 7,
      period: 6,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Os',
      name: 'Osmium',
      atomicNumber: 76,
      group: 8,
      period: 6,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Ir',
      name: 'Iridium',
      atomicNumber: 77,
      group: 9,
      period: 6,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Pt',
      name: 'Platinum',
      atomicNumber: 78,
      group: 10,
      period: 6,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Au',
      name: 'Gold',
      atomicNumber: 79,
      group: 11,
      period: 6,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Hg',
      name: 'Mercury',
      atomicNumber: 80,
      group: 12,
      period: 6,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Tl',
      name: 'Thallium',
      atomicNumber: 81,
      group: 13,
      period: 6,
      type: 'Post-Transition-Metal',
    },
    {
      symbol: 'Pb',
      name: 'Lead',
      atomicNumber: 82,
      group: 14,
      period: 6,
      type: 'Post-Transition-Metal',
    },
    {
      symbol: 'Bi',
      name: 'Bismuth',
      atomicNumber: 83,
      group: 15,
      period: 6,
      type: 'Post-Transition-Metal',
    },
    {
      symbol: 'Po',
      name: 'Polonium',
      atomicNumber: 84,
      group: 16,
      period: 6,
      type: 'Metalloid',
    },
    {
      symbol: 'At',
      name: 'Astatine',
      atomicNumber: 85,
      group: 17,
      period: 6,
      type: 'Metalloid',
    },
    {
      symbol: 'Rn',
      name: 'Radon',
      atomicNumber: 86,
      group: 18,
      period: 6,
      type: 'Noble-Gas',
    },
    {
      symbol: 'Fr',
      name: 'Francium',
      atomicNumber: 87,
      group: 1,
      period: 7,
      type: 'Alkali-Metal',
    },
    {
      symbol: 'Ra',
      name: 'Radium',
      atomicNumber: 88,
      group: 2,
      period: 7,
      type: 'Alkali-Earth-Metal',
    },

    {
      symbol: 'Ac',
      name: 'Actinium',
      atomicNumber: 89,
      group: 4,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Th',
      name: 'Thorium',
      atomicNumber: 90,
      group: 5,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Pa',
      name: 'Protactinium',
      atomicNumber: 91,
      group: 6,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'U',
      name: 'Uranium',
      atomicNumber: 92,
      group: 7,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Np',
      name: 'Neptunium',
      atomicNumber: 93,
      group: 8,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Pu',
      name: 'Plutonium',
      atomicNumber: 94,
      group: 9,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Am',
      name: 'Americium',
      atomicNumber: 95,
      group: 10,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Cm',
      name: 'Curium',
      atomicNumber: 96,
      group: 11,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Bk',
      name: 'Berkelium',
      atomicNumber: 97,
      group: 12,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Cf',
      name: 'Californium',
      atomicNumber: 98,
      group: 13,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Es',
      name: 'Einsteinium',
      atomicNumber: 99,
      group: 14,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Fm',
      name: 'Fermium',
      atomicNumber: 100,
      group: 15,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Md',
      name: 'Mendelevium',
      atomicNumber: 101,
      group: 16,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'No',
      name: 'Nobelium',
      atomicNumber: 102,
      group: 17,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Lr',
      name: 'Lawrencium',
      atomicNumber: 103,
      group: 18,
      period: 9,
      type: 'Actinide',
    },
    {
      symbol: 'Rf',
      name: 'Rutherfordium',
      atomicNumber: 104,
      group: 4,
      period: 7,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Db',
      name: 'Dubnium',
      atomicNumber: 105,
      group: 5,
      period: 7,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Sg',
      name: 'Seaborgium',
      atomicNumber: 106,
      group: 6,
      period: 7,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Bh',
      name: 'Bohrium',
      atomicNumber: 107,
      group: 7,
      period: 7,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Hs',
      name: 'Hassium',
      atomicNumber: 108,
      group: 8,
      period: 7,
      type: 'Transition-Metal',
    },
    {
      symbol: 'Mt',
      name: 'Meitnerium',
      atomicNumber: 109,
      group: 9,
      period: 7,
      type: 'Undefined',
    },
    {
      symbol: 'Ds',
      name: 'Darmstadtium',
      atomicNumber: 110,
      group: 10,
      period: 7,
      type: 'Undefined',
    },
    {
      symbol: 'Rg',
      name: 'Roentgenium',
      atomicNumber: 111,
      group: 11,
      period: 7,
      type: 'Undefined',
    },
    {
      symbol: 'Cn',
      name: 'Copernicium',
      atomicNumber: 112,
      group: 12,
      period: 7,
      type: 'Undefined',
    },
    {
      symbol: 'Nh',
      name: 'Nihonium',
      atomicNumber: 113,
      group: 13,
      period: 7,
      type: 'Undefined',
    },
    {
      symbol: 'Fl',
      name: 'Flerovium',
      atomicNumber: 114,
      group: 14,
      period: 7,
      type: 'Undefined',
    },
    {
      symbol: 'Mc',
      name: 'Moscovium',
      atomicNumber: 115,
      group: 15,
      period: 7,
      type: 'Undefined',
    },
    {
      symbol: 'Lv',
      name: 'Livermorium',
      atomicNumber: 116,
      group: 16,
      period: 7,
      type: 'Undefined',
    },
    {
      symbol: 'Ts',
      name: 'Tennessine',
      atomicNumber: 117,
      group: 17,
      period: 7,
      type: 'Undefined',
    },
    {
      symbol: 'Og',
      name: 'Oganesson',
      atomicNumber: 118,
      group: 18,
      period: 7,
      type: 'Undefined',
    },
    {
      symbol: '',
      name: '',
      atomicNumber: 0,
      group: 0,
      period: 0,
      type: 'LaAcBlock',
    },
  ];
}
