// ─── Configuração visual de cada propriedade ──────────────────────────────────
// Adicione novas propriedades aqui conforme o backend for crescendo.

export const SERIES_CONFIG = [
  {
    id: 'atomic_number',
    label: 'Número atômico',
    unit: '',
    color: '#378ADD',
    pointStyle: 'rect',
  },
  {
    id: 'atomic_mass',
    label: 'Massa atômica',
    unit: 'u',
    color: '#7F77DD',
    pointStyle: 'circle',
  },
  {
    id: 'electronegativity',
    label: 'Eletronegatividade',
    unit: '',
    color: '#D85A30',
    pointStyle: 'triangle',
  },
  {
    id: 'ionization_energy',
    label: 'Energia de ionização',
    unit: 'eV',
    color: '#D4537E',
    pointStyle: 'cross',
  },
  {
    id: 'atomic_radius',
    label: 'Raio atômico',
    unit: 'pm',
    color: '#1D9E75',
    pointStyle: 'triangle',
  },
  {
    id: 'density',
    label: 'Densidade',
    unit: 'g/cm³',
    color: '#BA7517',
    pointStyle: 'rect',
  },
  {
    id: 'boiling_point',
    label: 'Ponto de ebulição',
    unit: 'K',
    color: '#9FE1CB',
    pointStyle: 'circle',
  },
  {
    id: 'melting_point',
    label: 'Ponto de fusão',
    unit: 'K',
    color: '#FAC775',
    pointStyle: 'cross',
  },
  {
    id: 'electron_affinity',
    label: 'Afinidade eletrônica',
    unit: 'eV',
    color: '#AFA9EC',
    pointStyle: 'circle',
  },
] as const;

export type SeriesId = (typeof SERIES_CONFIG)[number]['id'];

// ─── Dados mock — primeiros 36 elementos (H → Kr) ─────────────────────────────
// Substitua por chamada real ao FastAPI quando o endpoint estiver pronto.
// Cada linha é um Record<SeriesId | 'symbol', number | string>.

export const MOCK_ELEMENT_DATA: Record<string, number | string>[] = [
  {
    symbol: 'H',
    atomic_number: 1,
    atomic_mass: 1.008,
    electronegativity: 2.2,
    ionization_energy: 13.6,
    atomic_radius: 53,
    density: 0.09,
    boiling_point: 20.3,
    melting_point: 14.0,
    electron_affinity: 0.75,
  },
  {
    symbol: 'He',
    atomic_number: 2,
    atomic_mass: 4.003,
    electronegativity: 0,
    ionization_energy: 24.59,
    atomic_radius: 31,
    density: 0.18,
    boiling_point: 4.2,
    melting_point: 0.95,
    electron_affinity: -0.5,
  },
  {
    symbol: 'Li',
    atomic_number: 3,
    atomic_mass: 6.941,
    electronegativity: 0.98,
    ionization_energy: 5.39,
    atomic_radius: 167,
    density: 0.53,
    boiling_point: 1615,
    melting_point: 453.7,
    electron_affinity: 0.62,
  },
  {
    symbol: 'Be',
    atomic_number: 4,
    atomic_mass: 9.012,
    electronegativity: 1.57,
    ionization_energy: 9.32,
    atomic_radius: 112,
    density: 1.85,
    boiling_point: 2742,
    melting_point: 1560,
    electron_affinity: -0.5,
  },
  {
    symbol: 'B',
    atomic_number: 5,
    atomic_mass: 10.81,
    electronegativity: 2.04,
    ionization_energy: 8.3,
    atomic_radius: 87,
    density: 2.34,
    boiling_point: 4200,
    melting_point: 2348,
    electron_affinity: 0.28,
  },
  {
    symbol: 'C',
    atomic_number: 6,
    atomic_mass: 12.011,
    electronegativity: 2.55,
    ionization_energy: 11.26,
    atomic_radius: 67,
    density: 2.27,
    boiling_point: 4300,
    melting_point: 3823,
    electron_affinity: 1.26,
  },
  {
    symbol: 'N',
    atomic_number: 7,
    atomic_mass: 14.007,
    electronegativity: 3.04,
    ionization_energy: 14.53,
    atomic_radius: 56,
    density: 1.25,
    boiling_point: 77.4,
    melting_point: 63.2,
    electron_affinity: -0.07,
  },
  {
    symbol: 'O',
    atomic_number: 8,
    atomic_mass: 15.999,
    electronegativity: 3.44,
    ionization_energy: 13.62,
    atomic_radius: 48,
    density: 1.43,
    boiling_point: 90.2,
    melting_point: 54.4,
    electron_affinity: 1.46,
  },
  {
    symbol: 'F',
    atomic_number: 9,
    atomic_mass: 18.998,
    electronegativity: 3.98,
    ionization_energy: 17.42,
    atomic_radius: 42,
    density: 1.7,
    boiling_point: 85.0,
    melting_point: 53.5,
    electron_affinity: 3.4,
  },
  {
    symbol: 'Ne',
    atomic_number: 10,
    atomic_mass: 20.18,
    electronegativity: 0,
    ionization_energy: 21.56,
    atomic_radius: 38,
    density: 0.9,
    boiling_point: 27.1,
    melting_point: 24.6,
    electron_affinity: -1.2,
  },
  {
    symbol: 'Na',
    atomic_number: 11,
    atomic_mass: 22.99,
    electronegativity: 0.93,
    ionization_energy: 5.14,
    atomic_radius: 186,
    density: 0.97,
    boiling_point: 1156,
    melting_point: 370.9,
    electron_affinity: 0.55,
  },
  {
    symbol: 'Mg',
    atomic_number: 12,
    atomic_mass: 24.305,
    electronegativity: 1.31,
    ionization_energy: 7.65,
    atomic_radius: 160,
    density: 1.74,
    boiling_point: 1363,
    melting_point: 923.0,
    electron_affinity: -0.4,
  },
  {
    symbol: 'Al',
    atomic_number: 13,
    atomic_mass: 26.982,
    electronegativity: 1.61,
    ionization_energy: 5.99,
    atomic_radius: 143,
    density: 2.7,
    boiling_point: 2792,
    melting_point: 933.5,
    electron_affinity: 0.43,
  },
  {
    symbol: 'Si',
    atomic_number: 14,
    atomic_mass: 28.085,
    electronegativity: 1.9,
    ionization_energy: 8.15,
    atomic_radius: 117,
    density: 2.33,
    boiling_point: 3538,
    melting_point: 1687,
    electron_affinity: 1.39,
  },
  {
    symbol: 'P',
    atomic_number: 15,
    atomic_mass: 30.974,
    electronegativity: 2.19,
    ionization_energy: 10.49,
    atomic_radius: 98,
    density: 1.82,
    boiling_point: 553,
    melting_point: 317.3,
    electron_affinity: 0.75,
  },
  {
    symbol: 'S',
    atomic_number: 16,
    atomic_mass: 32.06,
    electronegativity: 2.58,
    ionization_energy: 10.36,
    atomic_radius: 88,
    density: 2.07,
    boiling_point: 717.8,
    melting_point: 388.4,
    electron_affinity: 2.08,
  },
  {
    symbol: 'Cl',
    atomic_number: 17,
    atomic_mass: 35.45,
    electronegativity: 3.16,
    ionization_energy: 12.97,
    atomic_radius: 79,
    density: 3.21,
    boiling_point: 239.1,
    melting_point: 171.6,
    electron_affinity: 3.61,
  },
  {
    symbol: 'Ar',
    atomic_number: 18,
    atomic_mass: 39.948,
    electronegativity: 0,
    ionization_energy: 15.76,
    atomic_radius: 71,
    density: 1.78,
    boiling_point: 87.3,
    melting_point: 83.8,
    electron_affinity: -1.0,
  },
  {
    symbol: 'K',
    atomic_number: 19,
    atomic_mass: 39.098,
    electronegativity: 0.82,
    ionization_energy: 4.34,
    atomic_radius: 227,
    density: 0.86,
    boiling_point: 1032,
    melting_point: 336.7,
    electron_affinity: 0.5,
  },
  {
    symbol: 'Ca',
    atomic_number: 20,
    atomic_mass: 40.078,
    electronegativity: 1.0,
    ionization_energy: 6.11,
    atomic_radius: 197,
    density: 1.54,
    boiling_point: 1757,
    melting_point: 1115,
    electron_affinity: 0.02,
  },
  {
    symbol: 'Sc',
    atomic_number: 21,
    atomic_mass: 44.956,
    electronegativity: 1.36,
    ionization_energy: 6.56,
    atomic_radius: 162,
    density: 2.99,
    boiling_point: 3109,
    melting_point: 1814,
    electron_affinity: 0.19,
  },
  {
    symbol: 'Ti',
    atomic_number: 22,
    atomic_mass: 47.867,
    electronegativity: 1.54,
    ionization_energy: 6.83,
    atomic_radius: 147,
    density: 4.51,
    boiling_point: 3560,
    melting_point: 1941,
    electron_affinity: 0.08,
  },
  {
    symbol: 'V',
    atomic_number: 23,
    atomic_mass: 50.942,
    electronegativity: 1.63,
    ionization_energy: 6.75,
    atomic_radius: 134,
    density: 6.11,
    boiling_point: 3680,
    melting_point: 2183,
    electron_affinity: 0.53,
  },
  {
    symbol: 'Cr',
    atomic_number: 24,
    atomic_mass: 51.996,
    electronegativity: 1.66,
    ionization_energy: 6.77,
    atomic_radius: 128,
    density: 7.19,
    boiling_point: 2944,
    melting_point: 2180,
    electron_affinity: 0.67,
  },
  {
    symbol: 'Mn',
    atomic_number: 25,
    atomic_mass: 54.938,
    electronegativity: 1.55,
    ionization_energy: 7.43,
    atomic_radius: 127,
    density: 7.43,
    boiling_point: 2334,
    melting_point: 1519,
    electron_affinity: -1.0,
  },
  {
    symbol: 'Fe',
    atomic_number: 26,
    atomic_mass: 55.845,
    electronegativity: 1.83,
    ionization_energy: 7.9,
    atomic_radius: 126,
    density: 7.87,
    boiling_point: 3134,
    melting_point: 1811,
    electron_affinity: 0.15,
  },
  {
    symbol: 'Co',
    atomic_number: 27,
    atomic_mass: 58.933,
    electronegativity: 1.88,
    ionization_energy: 7.88,
    atomic_radius: 125,
    density: 8.9,
    boiling_point: 3200,
    melting_point: 1768,
    electron_affinity: 0.66,
  },
  {
    symbol: 'Ni',
    atomic_number: 28,
    atomic_mass: 58.693,
    electronegativity: 1.91,
    ionization_energy: 7.64,
    atomic_radius: 124,
    density: 8.91,
    boiling_point: 3186,
    melting_point: 1728,
    electron_affinity: 1.16,
  },
  {
    symbol: 'Cu',
    atomic_number: 29,
    atomic_mass: 63.546,
    electronegativity: 1.9,
    ionization_energy: 7.73,
    atomic_radius: 128,
    density: 8.96,
    boiling_point: 2835,
    melting_point: 1358,
    electron_affinity: 1.24,
  },
  {
    symbol: 'Zn',
    atomic_number: 30,
    atomic_mass: 65.38,
    electronegativity: 1.65,
    ionization_energy: 9.39,
    atomic_radius: 134,
    density: 7.13,
    boiling_point: 1180,
    melting_point: 693.0,
    electron_affinity: -0.6,
  },
  {
    symbol: 'Ga',
    atomic_number: 31,
    atomic_mass: 69.723,
    electronegativity: 1.81,
    ionization_energy: 5.999,
    atomic_radius: 135,
    density: 5.91,
    boiling_point: 2477,
    melting_point: 302.9,
    electron_affinity: 0.41,
  },
  {
    symbol: 'Ge',
    atomic_number: 32,
    atomic_mass: 72.63,
    electronegativity: 2.01,
    ionization_energy: 7.9,
    atomic_radius: 122,
    density: 5.32,
    boiling_point: 3093,
    melting_point: 1211,
    electron_affinity: 1.23,
  },
  {
    symbol: 'As',
    atomic_number: 33,
    atomic_mass: 74.922,
    electronegativity: 2.18,
    ionization_energy: 9.79,
    atomic_radius: 119,
    density: 5.73,
    boiling_point: 887,
    melting_point: 1090,
    electron_affinity: 0.81,
  },
  {
    symbol: 'Se',
    atomic_number: 34,
    atomic_mass: 78.971,
    electronegativity: 2.55,
    ionization_energy: 9.75,
    atomic_radius: 116,
    density: 4.81,
    boiling_point: 958,
    melting_point: 494.0,
    electron_affinity: 2.02,
  },
  {
    symbol: 'Br',
    atomic_number: 35,
    atomic_mass: 79.904,
    electronegativity: 2.96,
    ionization_energy: 11.81,
    atomic_radius: 114,
    density: 3.12,
    boiling_point: 332,
    melting_point: 265.9,
    electron_affinity: 3.36,
  },
  {
    symbol: 'Kr',
    atomic_number: 36,
    atomic_mass: 83.798,
    electronegativity: 3.0,
    ionization_energy: 14.0,
    atomic_radius: 110,
    density: 3.75,
    boiling_point: 119.9,
    melting_point: 115.8,
    electron_affinity: -1.0,
  },
];
