export interface IElement {
  simbolo: string;
  nome: string;
  numeroAtomico: number | null;
  massaAtomica: number;
  grupo: number;
  serie: string;
  periodo: number;
  configuracaoEletronica: string;
  descricao?: string;
  abundanciaCrosta: number;
  abundanciaMar: number;
  densidade: number;
  raioAtomico: number;
  usos: string;
  eletronegatividade: number;
  condutividadeTermica: number;
  capacidadeCalorifica: number;
  capacidadeCalorificaMolar: number;
  radioativo: boolean;
  classeGeoquimica: string;
  calorEvaporacao: number;
  calorFusao: number;
  CAS: string;
  temperaturaFusao: number;
  temperaturaEbulicao: number;
  temperaturaCritica: number;
  pressaoCritica: number;
  fontes: string;
  descobridor: string;
  localDescoberta: string;
  anoDescoberta: number;
  origemNome: string;
  tipo: string;
  link?: string;
  link_nist?: string;
  spectral_lines?: [number, number][];
  protons: number;
  neutrons: number;
}
